//Map coords - source coordinates of this tiles in tile map

export const tiles = {
  house: {
    type: 'house',
    mapX: 32,
    mapY: 0,
    width: 16,
    height: 16,
  },
  houseStage1: {
    type: 'houseStage1',
    mapX: 0,
    mapY: 0,
    width: 16,
    height: 16,
  },
  houseStage2: {
    type: 'houseStage2',
    mapX: 16,
    mapY: 0,
    width: 16,
    height: 16,
  },
  houseSide: {
    type: 'houseSide',
    mapX: 32,
    mapY: 16,
    width: 16,
    height: 16,
  },
  houseSideStage1: {
    type: 'houseSideStage1',
    mapX: 0,
    mapY: 16,
    width: 16,
    height: 16,
  },
  houseSideStage2: {
    type: 'houseSideStage2',
    mapX: 16,
    mapY: 16,
    width: 16,
    height: 16,
  },
  houseDouble: {
    type: 'houseDouble',
    mapX: 32,
    mapY: 32,
    width: 16,
    height: 16,
  },
  houseDoubleStage1: {
    type: 'houseDoubleStage1',
    mapX: 0,
    mapY: 32,
    width: 16,
    height: 16,
  },
  houseDoubleStage2: {
    type: 'houseDoubleStage2',
    mapX: 16,
    mapY: 32,
    width: 16,
    height: 16,
  },
  houseBlacksmith: {
    type: 'houseBlacksmith',
    mapX: 32,
    mapY: 48,
    width: 16,
    height: 16,
  },
  houseBlacksmithStage1: {
    type: 'houseBlacksmithStage1',
    mapX: 0,
    mapY: 48,
    width: 16,
    height: 16,
  },
  houseBlacksmithStage2: {
    type: 'houseBlacksmithStage2',
    mapX: 16,
    mapY: 48,
    width: 16,
    height: 16,
  },
  houseFarm: {
    type: 'houseFarm',
    mapX: 32,
    mapY: 64,
    width: 16,
    height: 16,
  },
  houseFarmStage1: {
    type: 'houseFarmStage1',
    mapX: 0,
    mapY: 64,
    width: 16,
    height: 16,
  },
  houseFarmStage2: {
    type: 'houseFarmStage2',
    mapX: 16,
    mapY: 64,
    width: 16,
    height: 16,
  },
  houseBarn: {
    type: 'houseBarn',
    mapX: 32,
    mapY: 80,
    width: 16,
    height: 16,
  },
  houseBarnStage1: {
    type: 'houseBarnStage1',
    mapX: 0,
    mapY: 80,
    width: 16,
    height: 16,
  },
  houseBarnStage2: {
    type: 'houseBarnStage2',
    mapX: 16,
    mapY: 80,
    width: 16,
    height: 16,
  },
  houseBarnSide: {
    type: 'houseBarnSide',
    mapX: 32,
    mapY: 96,
    width: 16,
    height: 16,
  },
  houseBarnSideStage1: {
    type: 'houseBarnSideStage1',
    mapX: 0,
    mapY: 96,
    width: 16,
    height: 16,
  },
  houseBarnSideStage2: {
    type: 'houseBarnSideStage2',
    mapX: 16,
    mapY: 96,
    width: 16,
    height: 16,
  },
  market: {
    type: 'market',
    mapX: 32,
    mapY: 112,
    width: 16,
    height: 16,
  },
  marketStage1: {
    type: 'marketStage1',
    mapX: 0,
    mapY: 112,
    width: 16,
    height: 16,
  },
  marketStage2: {
    type: 'marketStage2',
    mapX: 16,
    mapY: 112,
    width: 16,
    height: 16,
  },
  castle: {
    type: 'castle',
    mapX: 48,
    mapY: 64,
    width: 32,
    height: 32,
  },
  castleStage1: {
    type: 'castleStage1',
    mapX: 48,
    mapY: 0,
    width: 32,
    height: 32,
  },
  castleStage2: {
    type: 'castleStage2',
    mapX: 48,
    mapY: 32,
    width: 32,
    height: 32,
  },
};
